<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" Theme="Theme1" %>
<%@ Register assembly="System.Web.DataVisualization,
Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
namespace="System.Web.UI.DataVisualization.Charting" tagprefix="asp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
<div id="wrap">
    <form id="form1" runat="server">
    <div id="header">
        <h1>Employee Membership</h1>
    </div>
    <div>
        <br />
        <!-- Search Controls --> 
        <asp:Label id="lblSearch" Text="Search: " runat="server" />
        <asp:TextBox ID="txtSearch" runat="server" />
        <asp:Button ID="btnSearch" Text="Search" OnClick="SearchMembers" ValidationGroup="SearchVal" runat="server" EnableViewState="False" />
        <asp:RequiredFieldValidator ID="rqdSearch" ControlToValidate="txtSearch" ValidationGroup="SearchVal" Text="(Required)" runat="server" />
        <br />
        
        <asp:SqlDataSource ID="SqlDataSource1" 
        ConnectionString="Data Source=.\SQLExpress;
                        AttachDbFilename=|DataDirectory|employees.mdf;
                        Integrated Security=True; User Instance=True"
        SelectCommand="SELECT * FROM membership where MembershipId like @SearchValue or FirstName like @SearchValue or LastName like @SearchValue"
        UpdateCommand="Update membership SET FirstName=@FirstName,LastName=@LastName,MembershipClass=@MembershipClass,VerificationCode=@VerificationCode where MembershipID=@membershipID" 
        DeleteCommand="DELETE FROM membership WHERE MembershipId=@MembershipID"
        runat="server" >
        <SelectParameters>
            <asp:ControlParameter ControlID="txtSearch" Name="SearchValue" PropertyName="Text" />
        </SelectParameters>
        </asp:SqlDataSource>
        
        <br />
        <asp:GridView ID="grdvMem" AutoGenerateColumns="False" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="MembershipId" AllowPaging="True" runat="server">
            <Columns>
            <asp:BoundField DataField="MembershipID" HeaderText="Membership ID" />
            <asp:BoundField DataField="FirstName" HeaderText="Last Name" />
            <asp:BoundField DataField="LastName" HeaderText="Last Name" />
            <asp:BoundField DataField="MembershipClass" HeaderText="Membership Class" />
            <asp:BoundField DataField="VerificationCode" HeaderText="Verification Code" />
            <asp:BoundField DataField="birth_date" Visible="false" HeaderText="Birth Date" />
            <asp:BoundField DataField="salary" Visible="false" HeaderText="Salary" />
            </Columns>
        </asp:GridView>
        <hr />
        
        <!-- Add Member Controls -->
        <div id="left">
        <table>  
            <tr>
            <td>
                <asp:Label ID="lblFirstName" Text="First Name:" AssociatedControlID="txtFirstName" runat="server" />
            </td>
            <td>
                <asp:TextBox ID="txtFirstName" runat="server" />
                <asp:RequiredFieldValidator ID="reqFName" ControlToValidate="txtFirstName" ValidationGroup="AddMemVal" Text="(Required)" runat="server" />
            </td>
            </tr>
            <tr>
            <td>
                <asp:Label ID="lblLastName" Text="Last Name:" AssociatedControlID="txtLastName" runat="server" />
            </td>
            <td>
                <asp:TextBox ID="txtLastName" runat="server" />
                <asp:RequiredFieldValidator ID="reqLName" ControlToValidate="txtLastName" ValidationGroup="AddMemVal" Text="(Required)" runat="server" />
            </td>
            </tr>
            <tr>
            <td>
                <asp:Label ID="lblMembershipClass" Text="Membership Class:" AssociatedControlID="txtMemClass" runat="server" />
            </td>
            <td>
                <asp:DropDownList ID="txtMemClass" runat="server">
                <asp:ListItem>none</asp:ListItem>
                <asp:ListItem>Gold</asp:ListItem>
                <asp:ListItem>Silver</asp:ListItem>
                <asp:ListItem>Regular</asp:ListItem>
                </asp:DropDownList>
            </td>
            </tr>
            <tr>
            <td>
                <asp:Label ID="lblBirthDate" Text="Birth Date: " runat="server" />
            </td>
            <td>
                <asp:TextBox ID="txtBirthDate" runat="server" />
                <asp:RequiredFieldValidator ID="reqBDate" ControlToValidate="txtBirthDate" ValidationGroup="AddMemVal" Text="(Required)" runat="server" />
                <asp:CompareValidator ID="cmpDate" ControlToValidate="txtBirthDate" ValidationGroup="AddMemVal" Text="(Invalid Date)" Operator="DataTypeCheck" Type="Date" runat="server" />
            </td>
            </tr>
            <tr>
            <td>
                <asp:Label ID="lblSalary" Text="Salary: " runat="server" />
            </td>
            <td>
                <asp:TextBox ID="txtSalary" runat="server" />
                <asp:RequiredFieldValidator ID="reqSalary" ControlToValidate="txtSalary" ValidationGroup="AddMemVal" Text="(Required)" runat="server" />
            </td>
            </tr>
        </table>
        <asp:Button ID="btnAdd" Text="Add Member" OnClick="btnAdd_Click" ValidationGroup="AddMemVal" runat="server" />
        <br />
        <asp:Label ID="lblError" runat="server" />
        </div>
        
        <!-- Verify and Delete member controls -->
        <div id="right">
        <asp:Label ID="Label1" Text="Verify Member by Id: " runat="server" />
        <br />
        <asp:TextBox ID="txtVerifyId" runat="server" />
        <asp:Button ID="Button1" Text="Verify Member" OnClick="btnVerify_Click" runat="server" ValidationGroup="VerMemVal" />
        <asp:RequiredFieldValidator ID="rqdVerId" ControlToValidate="txtVerifyId" ValidationGroup="VerMemVal" Text="(Required)" runat="server" />
        <br />
        <asp:CompareValidator ID="cmpVerId" ControlToValidate="txtVerifyId" ValidationGroup="VerMemVal" Text="(Must be a number)" Operator="DataTypeCheck" Type="Integer" runat="server" />
        <br />
        <asp:Label ID="lblVerify" runat="server" />
        </div>
        <hr />
        <asp:Button ID="Button2" Text="Show Charts" OnClick="display_charts" runat="server"  />
        <asp:Button ID="Button3" Text="Hide Charts" OnClick="hide_charts" runat="server"  />
        <br /><br />
        <!-- Salary Histogram -->
        <h5>Salary Histogram:</h5>
        <asp:SqlDataSource ID="SqlDataSource2" 
        ConnectionString="Data Source=.\SQLExpress; AttachDbFilename=|DataDirectory|employees.mdf; Integrated Security=True; User Instance=True"
        SelectCommand="select MembershipId,salary from membership order by MembershipId"
        runat="server" >      
        </asp:SqlDataSource>
        
        <asp:Chart ID="chtSalary" Visible="false" DataSourceID="SqlDataSource2" Width="800" runat="server">
        <series>
            <asp:Series Name="Series1" XValueMember="MembershipId" YValueMembers="salary" ChartType="Column">
        </asp:Series>
        </series>
        <chartareas>
            <asp:ChartArea BackColor="NavajoWhite" BackGradientStyle="LeftRight" 
                Name="ChartArea1" ShadowOffset="5">
                <AxisX Title="Employees" />
                <AxisY Title="Salary" />
            </asp:ChartArea>
        </chartareas>
        </asp:Chart>
        
        <!-- Age Histogram -->
        <h5>Age Histogram:</h5>
        <asp:SqlDataSource ID="SqlDataSource3" 
        ConnectionString="Data Source=.\SQLExpress; AttachDbFilename=|DataDirectory|employees.mdf; Integrated Security=True; User Instance=True"
        SelectCommand="select MembershipId,birth_date from membership order by MembershipId"
        runat="server" >      
        </asp:SqlDataSource>
        
        <asp:Chart ID="Chart1" Visible="false" DataSourceID="SqlDataSource3" Width="800" runat="server">
        <series>
            <asp:Series Name="Series1" XValueMember="MembershipId" YValueMembers="birth_date" ChartType="Column">
        </asp:Series>
        </series>
        <chartareas>
            <asp:ChartArea  BackColor="NavajoWhite" BackGradientStyle="LeftRight" 
                Name="ChartArea1" ShadowOffset="5">
                <AxisX Title="Employees" />
                <AxisY Title="Age" />
            </asp:ChartArea>
        </chartareas>
        </asp:Chart>

        <!-- silver class histogram -->
        <h5>Highest Salary of Silver Class (top 5%):</h5>
        <asp:SqlDataSource ID="SqlDataSource4" 
        ConnectionString="Data Source=.\SQLExpress; AttachDbFilename=|DataDirectory|employees.mdf; Integrated Security=True; User Instance=True"
        SelectCommand="select top 5 percent MembershipId,membershipclass,salary from membership where membershipclass='Silver' order by membershipId"
        runat="server" >      
        </asp:SqlDataSource>
        
        <asp:Chart ID="Chart2" Visible="false" DataSourceID="SqlDataSource4"  Width="800" runat="server">
        <series>
            <asp:Series Name="Series1" XValueMember="MembershipId" YValueMembers="salary" ChartType="Column">
        </asp:Series>
        </series>
        <chartareas>
            <asp:ChartArea BackColor="NavajoWhite" BackGradientStyle="LeftRight" 
                Name="ChartArea1" ShadowOffset="5">
                <AxisX Title="Employees" />
                <AxisY Title="Salary" />
            </asp:ChartArea>
        </chartareas>
        </asp:Chart>
        
    </div>
    </form>
</div>
</body>
</html>
